## Link para o Dataset utilizado:

1. [Obesity among adults by country, 1975-2016](https://www.kaggle.com/amanarora/obesity-among-adults-by-country-19752016/)

Tais conjuntos de dados são públicos foram publicados no Kaggle. Mais instruções sobre cada um deles podem ser encontrados no link acima.

In [151]:
import pandas as pd
import numpy as np

## Perguntas - Obesity among adults by country, 1975-2016

In [154]:
df_obesity = pd.read_csv("obesity_cleaned.csv")
df_obesity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24570 entries, 0 to 24569
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   24570 non-null  int64
 1   Country      24570 non-null  object
 2   Year         24570 non-null  int64
 3   Obesity (%)  24570 non-null  object
 4   Sex          24570 non-null  object
dtypes: int64(2), object(3)
memory usage: 959.9+ KB

In [156]:
df_obesity.head()

   Unnamed: 0      Country  Year    Obesity (%)         Sex
0           0  Afghanistan  1975  0.5 [0.2-1.1]  Both sexes
1           1  Afghanistan  1975  0.2 [0.0-0.6]        Male
2           2  Afghanistan  1975  0.8 [0.2-2.0]      Female
3           3  Afghanistan  1976  0.5 [0.2-1.1]  Both sexes
4           4  Afghanistan  1976  0.2 [0.0-0.7]        Male

In [158]:
df_obesity.drop('Unnamed: 0', axis=1, inplace=True)

In [160]:
df_obesity.head()

       Country  Year    Obesity (%)         Sex
0  Afghanistan  1975  0.5 [0.2-1.1]  Both sexes
1  Afghanistan  1975  0.2 [0.0-0.6]        Male
2  Afghanistan  1975  0.8 [0.2-2.0]      Female
3  Afghanistan  1976  0.5 [0.2-1.1]  Both sexes
4  Afghanistan  1976  0.2 [0.0-0.7]        Male

In [162]:
df_obesity['(%)'] = df_obesity['Obesity (%)'].str.extract(r'\[(.*)\]')

- Limpe os dados do DataFrame, criando uma coluna de nome 'Obesity' que conterá os valores de obesidade. Transforme em float as colunas que porventura foram importadas como string.

In [165]:
df_obesity['Obesity'] = df_obesity['Obesity (%)'].str.split(' ')

In [167]:
df_obesity

           Country  Year       Obesity (%)         Sex           Obesity
0      Afghanistan  1975     0.5 [0.2-1.1]  Both sexes     0.5 [0.2-1.1]
1      Afghanistan  1975     0.2 [0.0-0.6]        Male     0.2 [0.0-0.6]
2      Afghanistan  1975     0.8 [0.2-2.0]      Female     0.8 [0.2-2.0]
3      Afghanistan  1976     0.5 [0.2-1.1]  Both sexes     0.5 [0.2-1.1]
4      Afghanistan  1976     0.2 [0.0-0.7]        Male     0.2 [0.0-0.7]
...            ...   ...               ...         ...               ...
24565     Zimbabwe  2015     4.5 [2.4-7.6]        Male     4.5 [2.4-7.6]
24566     Zimbabwe  2015  24.8 [18.9-31.3]      Female  24.8 [18.9-31.3]
24567     Zimbabwe  2016  15.5 [12.0-19.2]  Both sexes  15.5 [12.0-19.2]
24568     Zimbabwe  2016     4.7 [2.5-8.0]        Male     4.7 [2.5-8.0]
24569     Zimbabwe  2016  25.3 [19.1-32.0]      Female  25.3 [19.1-32.0]

[24570 rows x 5 columns]

- Qual o percentual médio de obesidade por sexo no mundo no ano de 2015?

- Quais são os 5 países com a maior e a menor taxa de aumento nos índices de obesidade no período observado?

- Quais os países com maiores e menores níveis percetuais de obesidade em 2015?

- Qual a diferença média percentual de obesidade entre sexos ao longo dos anos para o Brasil?

- Você conseguiria plotar um gráfico mostrando a evolução da obesidade para ambos sexos no mundo?

In [ ]:
df_both.plot()

In [ ]:
df_gdp = pd.read_csv("Datasets/GDP.csv", decimal=".")

- Limpe o conjunto de dados, convertendo strings em datas ou float, quando necessário.

- Você conseguiria informar o primeiro valor registrado de cada país?

- Informe as regiões com maiores crescimentos de PIB per capita no século passado.

- Preecha os anos ausentes em cada país com uma estimativa, baseada na diferença entre o próximo registro e o anterior.

### DESAFIOS
- Você conseguiria criar um mapa do gdp ou da obesidade no mundo ao longo dos anos?

- Há uma relação entre níveis de obesidade e gdp per capita?